### PR TITLE
Add Continuous delivery for python module

### PR DESCRIPTION
**Pull request by rjanvier**
Hi,
I'm working on the 3DFin project @3DFin (we will soon release our tree segmentation lib and sofware). We use your algorithm on the project, thank you for making it open source. 

Actually you project need a compiler to use it (unless you use Conda) as there is now wheel (pre compiled python package) distributed in PyPI. This PR try to fill this gap in order to improve out-of-the-box experience on most OSes.

I summarize here the list of the changes as commit list is intricated (with small commits and back and forth changes on the API)
- Add a cibuild_wheels github workflow. The wheel is compiled for many version of python and OSes (Linux, Windows, macOS). At the end of the process the package is uploaded on PyPi (you have to setup a PyPi account, generate token and put it in your project secrets on github, I can provide a more detailed guidance uppon request). After that, each time you push a new tag on github, it will upload the version on PyPi and a simple build is triggered  on PR.
- Migrate from distutils to setuptools. Distutils is deprecated and will be removed in python 3.12
- Change the directory layout to have a better compliance with the structure of a python package (src package is now built correctly)
- Add and change some metadata to the project.  Among these changes: use "cloth_filter" as name of the package (as CSF is already used in PiPY, but CSF module structure is the same) and putted myself as a maintainer of the PyPi package (but it could be change once you make your own upload).
- Make openMP optional, in order to better comply with stock macOS compiler configuration (Clang from XCode does not support openMP)
- Change a bit the API. Change is backward compatible I just added a function to compute the cloth and output the cloth_node without having to make the full c2cdist classification against it.
- Removed the Anaconda subfolder, as now CSF is/will be available straight from PyPi for more architecture
- Increase version number

### CODE REVIEW

**Comment by jianboqi** [comment]
Thank you very much for your pull request, it is really an amazing feature that make CSF more convenient for users. I have tested your code, it works fine.

**Comment by jianboqi** [comment]
Dear @rjanvier , I have configed PYPI_TOKEN in github, but the build shows that the job "Publish to PyPI" was skipped, I failed to upload to pypi, do you have some experience about this?

**Comment by rjanvier** [comment]
Dear @jianboqi, thanks for your feedback. To upload a version on PyPI you have to tag it, see the condition here: https://github.com/jianboqi/CSF/blob/5162914e0ba7c2c9e6ac90c0579e58c4312e77b1/.github/workflows/wheels.yml#L41 Choose the convention you like, in general it's vN.N.N. Example for your current HEAD. `git tag v1.2.4 && git push --tag`. I have deleted my version from PyPI so the package name should be available for you.

**Comment by jianboqi** [comment]
Dear @rjanvier Thank you very much, I succeed to upload the package, now we can install by `pip install cloth-simulation-filter`, I really thank you for your effort to make CSF more available.

**Pull request merged**
