### PR TITLE
Remove duplicate include statements and change namespace calls

### PR DESCRIPTION
**Pull request by Crghilardi**
This pull request makes small changes to improve consistency and code style.

1. Remove duplicated `include` statements in `Cloth.h`
2. Remove instances of `using namespace std;` and modify to use `std::` consistently throughout the entire project
3. Comment out the `pragma omp` for loops that blocks compilation in `CSF.cpp` and `Cloth.cpp`. These were already commented out in `Rasterization.cpp`

This pull request only modifies the C++ files and CSFDemo. The python and matlab extension code is not changed at all. 
I have tested it locally on my computer and the project compiles and the demo runs on linux.

### CODE REVIEW

**Comment by jianboqi** [comment]
Hello Crghilardi,
    Thank you very much for providing this pull request. It makes the code more consistent. There is a problem that why you comment out the "pragma omp" for loops that blocks compilation in CSF.cpp and Cloth.cpp. We have tested before the compilition of the code under windows as well as linux, it works fine. What's your problem when you are compiling this code with "pragma omp".
   Actually, "pragma omp" is very important in Cloth.cpp (the following code), it will use the multiple cores of the computer to acceleration the filtering process, if it is commented out, the performance of CSF may be influenced a lot. I wish you could consider about this. Thank you!
Jianbo Qi


double Cloth::timeStep() {
    int particleCount = static_cast<int>(particles.size());	    int particleCount = static_cast<int>(particles.size());
    #pragma omp parallel for	    //#pragma omp parallel for
    for (int i = 0; i < particleCount; i++) {	    for (int i = 0; i < particleCount; i++) {
        particles[i].timeStep();	        particles[i].timeStep();
    }	    }


     #pragma omp parallel for	    //#pragma omp parallel for
    for (int j = 0; j < particleCount; j++) {	    for (int j = 0; j < particleCount; j++) {
        particles[j].satisfyConstraintSelf(constraint_iterations);	        particles[j].satisfyConstraintSelf(constraint_iterations);
    }	    }

**Comment by Crghilardi** [comment]
Hello,

I included that into this pull request because I was unable to compile `master` on my computer without the change. I get the same error messages as issue #19 on a linux (ubuntu) machine.

I can remove the `#pragma` changes from this pull request.

**Comment by Crghilardi** [comment]
After some testing I am able to fix the issue locally by using a newer version of `Cmake` (3.10). [There were changes to how it finds OpenMP in 3.9](https://stackoverflow.com/a/55148073/4206202). If interested I can submit another pull request with the update.

**Comment by jianboqi** [comment]
Hello,  
   Can you submit another pull request that removes the #pragma. Thank you for your nice work!
Jianbo Qi

**Comment by Crghilardi** [comment]
I removed the comments in the latest commit 6a048e6.
To confirm, did you want me to delete the statements completely?

**Comment by jianboqi** [comment]
Thank you very much, I have merged the code.

**Pull request merged**
