### PR TITLE
Add a correct way to input a numpy array

### PR DESCRIPTION
**Pull request by rjanvier**
Hi,
Numpy array input was far from being optimal. 
he plumbery with SWIG was previously not correctly put in place. As a result, CSF fallback to the `void CSF::setPointCloud(std::vector<std::vector<float> > points)` that pass the numpy array by value and thus makes two a full copies of the numpy array (and convert double coordinates to float).

This commit correct this behavior by providing correct SWIG bindings for numpy arrays.

### CODE REVIEW

**Comment by rjanvier** [comment]
PS once accepted and merged, could you please tag the commit on the main branch in order to release the wheels on PyPI?
thanks in advance.

**Comment by jvavrek** [comment]
I would highly appreciate this feature as well!

**Comment by rjanvier** [comment]
@jvavrek please look at this fork https://pypi.org/project/CSF-3DFin/

**Comment by jianboqi** [comment]
Thanks for the comtribution. I have merged the code, and new tag has been created.

**Comment by jvavrek** [comment]
This is great! For me, it turned a particularly large calculation from 5.5 minutes to 1.5 minutes.

**Pull request merged**
